In [44]:
import numpy as np
import scipy.linalg

In [56]:
# Cau 1

In [45]:
A = np.random.randint(1,11,size=(5,5))
A

array([[ 9, 10,  1,  3,  3],
       [ 6, 10,  3,  4,  4],
       [ 8,  3,  8,  6,  2],
       [10,  7,  5,  7,  6],
       [ 2,  2,  7,  7,  9]])

In [46]:
scipy.linalg.eig(A)

(array([28.18978835+0.j        ,  0.56294919+0.j        ,
         5.76209578+3.44961517j,  5.76209578-3.44961517j,
         2.72307091+0.j        ]),
 array([[-3.93301888e-01+0.j        , -1.41158457e-01+0.j        ,
          3.01646762e-01+0.183942j  ,  3.01646762e-01-0.183942j  ,
          1.52398629e-01+0.j        ],
        [-4.16502177e-01+0.j        ,  2.82869320e-04+0.j        ,
          3.79344992e-02+0.08448473j,  3.79344992e-02-0.08448473j,
         -2.66040185e-01+0.j        ],
        [-4.23878509e-01+0.j        , -4.43937131e-01+0.j        ,
          2.35212049e-01-0.47860353j,  2.35212049e-01+0.47860353j,
         -7.50106899e-01+0.j        ],
        [-5.47443984e-01+0.j        ,  8.35488927e-01+0.j        ,
          2.03745104e-02+0.02624495j,  2.03745104e-02-0.02624495j,
          4.75312549e-01+0.j        ],
        [-4.38715916e-01+0.j        , -2.91465756e-01+0.j        ,
         -7.62304339e-01+0.j        , -7.62304339e-01-0.j        ,
          3.42658573e-0

In [47]:
eig_value, eig_vector = scipy.linalg.eig(A)

In [48]:
A @ eig_vector[:,0]

array([-11.08709698+0.j, -11.74110823+0.j, -11.94904544+0.j,
       -15.43233005+0.j, -12.36730883+0.j])

In [52]:
eig_value[0] * eig_vector[:,0]

array([-11.08709698+0.j, -11.74110823+0.j, -11.94904544+0.j,
       -15.43233005+0.j, -12.36730883+0.j])

In [55]:
np.allclose(A @ eig_vector[:,0], eig_value[0] * eig_vector[:,0])

True

In [63]:
A1 = eig_vector @ np.diag(eig_value) @ np.linalg.inv(eig_vector)
A1.astype(float)

array([[ 9., 10.,  1.,  3.,  3.],
       [ 6., 10.,  3.,  4.,  4.],
       [ 8.,  3.,  8.,  6.,  2.],
       [10.,  7.,  5.,  7.,  6.],
       [ 2.,  2.,  7.,  7.,  9.]])

In [64]:
np.allclose(A1, A)

True

In [65]:
# Cau 2

In [69]:
P = np.random.randint(1,10,size=(4,4))
P

array([[4, 6, 2, 9],
       [3, 7, 3, 3],
       [8, 5, 2, 9],
       [8, 1, 6, 4]])

In [71]:
S = P @ P.T
S

array([[137,  87, 147,  86],
       [ 87,  76,  92,  61],
       [147,  92, 174, 117],
       [ 86,  61, 117, 117]])

In [72]:
q, lamda = scipy.linalg.eig(S)

In [73]:
q

array([437.04868896+0.j,  44.80206927+0.j,   2.65073783+0.j,
        19.49850395+0.j])

In [74]:
lamda

array([[-0.53616521, -0.45159393, -0.67574867,  0.22793313],
       [-0.36219822, -0.31099676,  0.20718859, -0.85391238],
       [-0.62227051, -0.02178158,  0.65347702,  0.43043322],
       [-0.44058906,  0.83598415, -0.27093248, -0.18332315]])