In [1]:
import numpy as np

In [2]:
A = np.random.randint(1,11, size=(4,6))
A

array([[ 8,  8,  9, 10,  7,  9],
       [ 8,  8, 10,  5,  7,  2],
       [ 7,  7,  9, 10,  1,  2],
       [ 9,  4,  5,  3,  8,  9]])

In [8]:
A_pesudo_inv = np.linalg.pinv(A)
A_pesudo_inv

array([[-0.2267886 , -0.04236157,  0.17937342,  0.20478031],
       [ 0.07337448,  0.06522978, -0.06058992, -0.08479676],
       [-0.00288989,  0.06400621, -0.00138499, -0.03396517],
       [ 0.08389033, -0.06601912,  0.03908756, -0.0542446 ],
       [ 0.09595928,  0.09717166, -0.15366012, -0.05954023],
       [ 0.08252264, -0.08655688, -0.02811754,  0.03389397]])

In [5]:
A @ A_pesudo_inv

array([[ 1.00000000e+00, -3.33066907e-16,  6.10622664e-16,
         9.99200722e-16],
       [-8.88178420e-16,  1.00000000e+00,  4.44089210e-16,
         6.66133815e-16],
       [-2.22044605e-16,  2.22044605e-16,  1.00000000e+00,
         2.22044605e-16],
       [-8.88178420e-16, -1.11022302e-16,  4.99600361e-16,
         1.00000000e+00]])

In [7]:
A_pesudo_inv @ A

array([[ 0.94543527, -0.07846626,  0.17354914, -0.0716188 , -0.06643536,
         0.07594902],
       [-0.07846626,  0.34551756,  0.34337499,  0.19960419,  0.23126577,
        -0.09352085],
       [ 0.17354914,  0.34337499,  0.43176238,  0.17538679,  0.15470791,
        -0.20645308],
       [-0.0716188 ,  0.19960419,  0.17538679,  0.7369495 , -0.26977078,
         0.21294847],
       [-0.06643536,  0.23126577,  0.15470791, -0.26977078,  0.72193463,
         0.21479454],
       [ 0.07594902, -0.09352085, -0.20645308,  0.21294847,  0.21479454,
         0.81840065]])

In [10]:
np.allclose(A, A @ A_pesudo_inv @ A)

True

In [11]:
np.allclose(A_pesudo_inv, A_pesudo_inv @ A @ A_pesudo_inv)

True