In [1]:
import numpy as np
import pandas as pd
import scipy.linalg

In [5]:
df = pd.read_csv('../Data/B2/iris.csv').iloc[:,:4]
df

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [6]:
np.linalg.svd(df)

(array([[-6.16171172e-02,  1.29969428e-01, -5.58364155e-05, ...,
         -9.34637342e-02, -9.60224157e-02, -8.09922905e-02],
        [-5.80722977e-02,  1.11371452e-01,  6.84386629e-02, ...,
          3.66755322e-02, -3.24463474e-02,  1.27273399e-02],
        [-5.67633852e-02,  1.18294769e-01,  2.31062793e-03, ...,
          3.08252776e-02,  1.95234663e-01,  1.35567696e-01],
        ...,
        [-9.40702260e-02, -4.98348018e-02, -4.14958083e-02, ...,
          9.81822841e-01, -2.17978813e-02, -8.85972146e-03],
        [-9.48993908e-02, -5.62107520e-02, -2.12386574e-01, ...,
         -2.14264126e-02,  9.42038920e-01, -2.96933496e-02],
        [-8.84882764e-02, -5.16210172e-02, -9.51442925e-02, ...,
         -8.52768485e-03, -3.02139863e-02,  9.73577349e-01]]),
 array([95.95066751, 17.72295328,  3.46929666,  1.87891236]),
 array([[-0.75116805, -0.37978837, -0.51315094, -0.16787934],
        [ 0.28583096,  0.54488976, -0.70889874, -0.34475845],
        [ 0.49942378, -0.67502499, -0.05471

In [7]:
u, s, vT = np.linalg.svd(df)

In [8]:
# 2 Singular value 3,4 co gia tri nho khi so sanh voi 2 Singular 1 va 2, nen co the giam demension xuong n = 2

In [9]:
n = 2

In [12]:
sigma_1_2 = np.diag(s[:n])
sigma_1_2

array([[95.95066751,  0.        ],
       [ 0.        , 17.72295328]])

In [16]:
df_new = pd.DataFrame(u[:, :n] @ sigma_1_2 @ vT[:n, :], columns=df.columns)
df_new

sepal_length  sepal_width  petal_length  petal_width
0        5.099453     3.500508      1.400946     0.198406
1        4.749747     3.191730      1.460070     0.254941
2        4.690479     3.210891      1.308639     0.191555
3        4.618348     3.084397      1.462666     0.267318
4        5.078961     3.500519      1.363524     0.183240
..            ...          ...           ...          ...
145      6.665127     2.997728      5.393597     1.869419
146      6.138637     2.688659      5.130763     1.795516
147      6.527667     2.946751      5.257866     1.819793
148      6.555130     2.915393      5.378797     1.872108
149      6.116299     2.726090      5.005468     1.740793

[150 rows x 4 columns]

In [17]:
df - df_new

sepal_length  sepal_width  petal_length  petal_width
0        0.000547    -0.000508     -0.000946     0.001594
1        0.150253    -0.191730     -0.060070    -0.054941
2        0.009521    -0.010891     -0.008639     0.008445
3       -0.018348     0.015603      0.037334    -0.067318
4       -0.078961     0.099481      0.036476     0.016760
..            ...          ...           ...          ...
145      0.034873     0.002272     -0.193597     0.430581
146      0.161363    -0.188659     -0.130763     0.104484
147     -0.027667     0.053249     -0.057866     0.180207
148     -0.355130     0.484607      0.021203     0.427892
149     -0.216299     0.273910      0.094532     0.059207

[150 rows x 4 columns]

In [21]:
# Create Sigma m x n = 150 x 4
sigma = np.pad(np.diag(s), ((0,150-4),(0,0)) )
sigma.shape

(150, 4)

In [23]:
df_re_create = pd.DataFrame(u @ sigma @ vT, columns=df.columns)
df_re_create

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [25]:
np.allclose(df, df_re_create)

True