In [1]:
import numpy as np
import pandas as pd
import scipy.linalg

In [6]:
df = pd.read_csv('../Data/B2/ex3.csv', index_col=0)
df

post1  post2  post3  post4
word                             
ice        4      4      6      2
snow       6      1      0      5
tahoe      3      0      0      5
goal       0      6      5      1
puck       0      4      5      0

In [7]:
u, s, vT = np.linalg.svd(df)

In [8]:
u

array([[-0.62610079,  0.01852561,  0.6259093 ,  0.23487748, -0.40090488],
       [-0.35134826, -0.67829097,  0.0779915 , -0.56006159,  0.311005  ],
       [-0.21940528, -0.51980146, -0.50346468,  0.6484906 , -0.08747016],
       [-0.51965373,  0.37026259, -0.59046979, -0.38005352, -0.31586445],
       [-0.40788911,  0.36371724, -0.00485878,  0.25726028,  0.79695031]])

In [9]:
s

array([13.3221948 ,  9.2609512 ,  2.41918664,  1.37892883])

In [10]:
vT

array([[-0.39563365, -0.57086917, -0.6301003 , -0.34721178],
       [-0.59983555,  0.33174302,  0.4082791 , -0.60286986],
       [ 0.60400142, -0.40535325,  0.32193174, -0.60599586],
       [-0.34475152, -0.63225288,  0.57675103,  0.38569539]])

In [11]:
df.shape

(5, 4)

In [14]:
sigma = np.pad(np.diag(s), ((0,1),(0,0)))
sigma

array([[13.3221948 ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  9.2609512 ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  2.41918664,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.37892883],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [26]:
df_re_create = u @ sigma @ vT
np.around(df_re_create, 2)

array([[ 4.,  4.,  6.,  2.],
       [ 6.,  1., -0.,  5.],
       [ 3.,  0., -0.,  5.],
       [ 0.,  6.,  5.,  1.],
       [ 0.,  4.,  5., -0.]])

In [27]:
np.allclose(df_re_create, df)

True

In [31]:
# Nhan xet: s value 2 gia tri dau tien lon, 2 gia tri sau nho nen co the luot bot 2 thanh phan, giam demension xuong con 2-D
n = 2

In [35]:
s_reduce = s[:2]
sigma_reduce = np.diag(s_reduce) # Size 2x2

In [36]:
u_reduce = u[:, :2] # Size 5 x 2
vT_reduce = vT[:2, :] # Size 2 x 4

In [37]:
df_new = u_reduce @ sigma_reduce @ vT_reduce
df_new

array([[ 3.19708412,  4.81855605,  5.32573599,  2.79267497],
       [ 5.61979298,  0.58820097,  0.38467542,  5.41220366],
       [ 4.04394318,  0.07166455, -0.12363886,  3.91701473],
       [ 0.68211703,  5.08962774,  5.76212157,  0.33649133],
       [ 0.12939801,  4.21952303,  4.79918534, -0.14394602]])

In [40]:
df - df_new

post1     post2     post3     post4
word                                         
ice    0.802916 -0.818556  0.674264 -0.792675
snow   0.380207  0.411799 -0.384675 -0.412204
tahoe -1.043943 -0.071665  0.123639  1.082985
goal  -0.682117  0.910372 -0.762122  0.663509
puck  -0.129398 -0.219523  0.200815  0.143946