In [34]:
import sklearn.datasets
import sklearn.decomposition
import scipy.sparse
import numpy as np

In [16]:
digits = sklearn.datasets.load_digits()
A = digits.data
A.shape

(1797, 64)

In [17]:
A

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [21]:
X = scipy.sparse.csr_matrix(A)
X

<1797x64 sparse matrix of type '<class 'numpy.float64'>'
	with 58736 stored elements in Compressed Sparse Row format>

In [12]:
svd = sklearn.decomposition.TruncatedSVD(n_components=10)

In [25]:
svd.fit_transform(A)

array([[ 45.86127719,  -1.19211455,  21.10005765, ...,   0.39803297,
          1.30943543,  -1.39046292],
       [ 55.52967927,   7.861773  , -20.48719597, ...,   1.53821878,
         -4.73966542,   3.41392921],
       [ 55.8278837 ,   6.91460197,  -9.66245091, ...,   2.29825199,
        -16.83956661,  -1.11664483],
       ...,
       [ 65.52698526,  10.65872655,  -6.29456233, ...,  -2.30196338,
         -4.47154834,  -1.72678692],
       [ 58.60616587,  -4.91124542,  12.72315307, ...,   0.51215581,
         -1.63131288,   6.44308776],
       [ 64.44823101,  -0.45551596,   7.04184122, ...,  -8.30302652,
          3.38039046,  -1.41544344]])

In [28]:
T = svd.fit_transform(X)

In [29]:
A_recreate = svd.inverse_transform(T)

In [26]:
# Original 1st row in A
A[0,:]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [41]:
# After svd reduction
T[0,:]

array([45.86127719, -1.19211604, 21.10005857, -9.48897034, 13.04309416,
       -7.01662177, -8.95995094,  0.39632548,  1.31009448, -1.39042409])

In [43]:
np.sum(svd.explained_variance_ratio_)

0.7324264603964306