In [26]:
import numpy as np
from sklearn.decomposition import PCA

In [2]:
np.random.seed(190)

In [3]:
A = np.random.randint(1,256,size=(3000,3))
A

array([[ 79, 141,  44],
       [ 38,  89, 111],
       [  4,  88, 105],
       ...,
       [ 58,  30,  46],
       [222,  39, 101],
       [231, 228, 173]])

In [18]:
# Cach 1: Dung sklearn PCA

In [4]:
pca = PCA(3)
pca.fit(A)

PCA(n_components=3)

In [5]:
T = pca.transform(A)
T

array([[ -66.55153416,    3.75775968,  -68.77147141],
       [ -23.06818757,  -78.18483555,  -52.38215614],
       [ -26.75764212,  -98.43140729,  -80.12137491],
       ...,
       [-107.24695672,  -91.31931987,  -23.27167441],
       [ -63.9237229 ,    2.29863061,  115.87133389],
       [  76.19053965,  126.97690536,   39.65243049]])

In [6]:
pca.inverse_transform(T)

array([[ 79., 141.,  44.],
       [ 38.,  89., 111.],
       [  4.,  88., 105.],
       ...,
       [ 58.,  30.,  46.],
       [222.,  39., 101.],
       [231., 228., 173.]])

In [19]:
# Cach 2: Dung u @ sigma

In [11]:
M = np.mean(A,axis=0)
M

array([126.01266667, 126.57733333, 126.186     ])

In [12]:
C = A - M

In [13]:
u, s, vT = np.linalg.svd(C)

In [14]:
sigma = np.pad(np.diag(s), ((0,3000-3),(0,0)))

In [15]:
u @ sigma

array([[ -66.55153416,    3.75775968,  -68.77147141],
       [ -23.06818757,  -78.18483555,  -52.38215614],
       [ -26.75764212,  -98.43140729,  -80.12137491],
       ...,
       [-107.24695672,  -91.31931987,  -23.27167441],
       [ -63.9237229 ,    2.29863061,  115.87133389],
       [  76.19053965,  126.97690536,   39.65243049]])