In [75]:
import numpy as np
import scipy
import scipy.linalg

In [76]:
A = np.array([[4,3], [8,6]])
A

array([[4, 3],
       [8, 6]])

In [77]:
scipy.linalg.svd(A)

(array([[-0.4472136 , -0.89442719],
        [-0.89442719,  0.4472136 ]]),
 array([1.11803399e+01, 1.15750506e-15]),
 array([[-0.8, -0.6],
        [-0.6,  0.8]]))

In [78]:
u, s, vT = scipy.linalg.svd(A)

In [79]:
u @ np.diag(s) @ vT

array([[4., 3.],
       [8., 6.]])

In [19]:
B = np.array([[1,2],[3,4],[5,6]])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
u, s, vT = scipy.linalg.svd(B)

In [63]:
u

array([[-0.2298477 ,  0.88346102,  0.40824829],
       [-0.52474482,  0.24078249, -0.81649658],
       [-0.81964194, -0.40189603,  0.40824829]])

In [73]:
sigma = np.pad(np.diag(s), ((0,1),(0,0)), mode='constant')

In [74]:
u @ sigma @ vT

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [83]:
D = np.arange(1,31).reshape(3,10)
D

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [85]:
scipy.linalg.svd(D)

(array([[-0.19101157,  0.89266338,  0.40824829],
        [-0.51371859,  0.26348917, -0.81649658],
        [-0.8364256 , -0.36568503,  0.40824829]]),
 array([9.69657342e+01, 7.25578339e+00, 5.82172067e-15]),
 array([[-0.24139304, -0.25728686, -0.27318068, -0.2890745 , -0.30496832,
         -0.32086214, -0.33675595, -0.35264977, -0.36854359, -0.38443741],
        [-0.53589546, -0.42695236, -0.31800926, -0.20906617, -0.10012307,
          0.00882003,  0.11776313,  0.22670623,  0.33564933,  0.44459242],
        [-0.76308471,  0.57981078,  0.1426451 ,  0.09783039,  0.10006951,
          0.08192046, -0.02182071, -0.07111153,  0.02343386, -0.16969316],
        [-0.11442628, -0.24159965, -0.22978376,  0.9248098 , -0.07469427,
         -0.07119775, -0.05510443, -0.0470247 , -0.06011372, -0.03086524],
        [-0.03428472, -0.13813055, -0.29451801, -0.06190924,  0.92563949,
         -0.08203999, -0.06968687, -0.07007771, -0.10413301, -0.07085938],
        [ 0.02720949, -0.03009057, -0.34021657, 

In [84]:
u, s, vT = scipy.linalg.svd(D)

In [86]:
n = 2

In [87]:
u[:,:n] @ np.diag(s[:n]) @ vT[:2,:]

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.]])

In [103]:
D @ vT[:2,:].T

array([[-18.52157747,   6.47697214],
       [-49.81310011,   1.91182038],
       [-81.10462276,  -2.65333138]])

In [91]:
u[:,:n] @ np.diag(s[:n])

array([[-18.52157747,   6.47697214],
       [-49.81310011,   1.91182038],
       [-81.10462276,  -2.65333138]])